version: '3.8'

services:
  # PostgreSQL for relayer state
  postgres:
    image: postgres:15-alpine
    container_name: fusion-postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=fusion
      - POSTGRES_PASSWORD=fusion123
      - POSTGRES_DB=fusion_relayer
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - fusion-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U fusion -d fusion_relayer"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Redis for caching
  redis:
    image: redis:7-alpine
    container_name: fusion-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - fusion-network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres-data:
  redis_data:

networks:
  fusion-network:
    driver: bridge 