# Hermes Configuration for 1inch Fusion+ Cosmos Extension
# This config supports Osmosis, Juno, and Cosmos Hub testnets

[global]
log_level = 'info'

[mode]

[mode.clients]
enabled = true
refresh = true
misbehaviour = true

[mode.connections]
enabled = false

[mode.channels]
enabled = false

[mode.packets]
enabled = true
clear_interval = 100
clear_on_start = true
tx_confirmation = true

[rest]
enabled = true
host = '127.0.0.1'
port = 3000

[telemetry]
enabled = true
host = '127.0.0.1'
port = 3001

# Osmosis Testnet
[[chains]]
id = 'osmo-test-5'
type = 'CosmosSdk'
rpc_addr = 'https://rpc.testnet.osmosis.zone:443'
grpc_addr = 'https://grpc.testnet.osmosis.zone:443'
event_source = { mode = 'push', url = 'wss://rpc.testnet.osmosis.zone:443/websocket', batch_delay = '500ms' }
rpc_timeout = '10s'
trusted_node = true
account_prefix = 'osmo'
key_name = 'relayer'
key_store_type = 'Test'
store_prefix = 'ibc'
default_gas = 100000
max_gas = 3000000
gas_price = { price = 0.025, denom = 'uosmo' }
gas_multiplier = 1.3
max_msg_num = 30
max_tx_size = 2097152
clock_drift = '5s'
max_block_time = '10s'
trusting_period = '336h'
trust_threshold = { numerator = '1', denominator = '3' }
address_type = { derivation = 'cosmos' }

[chains.packet_filter]
policy = 'allow'
list = [
  ['transfer', '*'],
  ['wasm.*', '*'],
]

# Juno Testnet
[[chains]]
id = 'uni-6'
type = 'CosmosSdk'
rpc_addr = 'https://rpc.testnet.juno.strange.love:443'
grpc_addr = 'https://grpc.testnet.juno.strange.love:443'
event_source = { mode = 'push', url = 'wss://rpc.testnet.juno.strange.love:443/websocket', batch_delay = '500ms' }
rpc_timeout = '10s'
trusted_node = true
account_prefix = 'juno'
key_name = 'relayer'
key_store_type = 'Test'
store_prefix = 'ibc'
default_gas = 100000
max_gas = 3000000
gas_price = { price = 0.075, denom = 'ujunox' }
gas_multiplier = 1.3
max_msg_num = 30
max_tx_size = 2097152
clock_drift = '5s'
max_block_time = '10s'
trusting_period = '336h'
trust_threshold = { numerator = '1', denominator = '3' }
address_type = { derivation = 'cosmos' }

[chains.packet_filter]
policy = 'allow'
list = [
  ['transfer', '*'],
  ['wasm.*', '*'],
]

# Cosmos Hub Testnet
[[chains]]
id = 'theta-testnet-001'
type = 'CosmosSdk'
rpc_addr = 'https://rpc.sentry-01.theta-testnet.polypore.xyz:443'
grpc_addr = 'https://grpc.sentry-01.theta-testnet.polypore.xyz:443'
event_source = { mode = 'push', url = 'wss://rpc.sentry-01.theta-testnet.polypore.xyz:443/websocket', batch_delay = '500ms' }
rpc_timeout = '10s'
trusted_node = true
account_prefix = 'cosmos'
key_name = 'relayer'
key_store_type = 'Test'
store_prefix = 'ibc'
default_gas = 100000
max_gas = 3000000
gas_price = { price = 0.025, denom = 'uatom' }
gas_multiplier = 1.3
max_msg_num = 30
max_tx_size = 2097152
clock_drift = '5s'
max_block_time = '10s'
trusting_period = '336h'
trust_threshold = { numerator = '1', denominator = '3' }
address_type = { derivation = 'cosmos' }

[chains.packet_filter]
policy = 'allow'
list = [
  ['transfer', '*'],
  ['wasm.*', '*'],
]