name: Deploy App
description: "Deploy the EVMore application"

on:
  push:
    branches: [ main ]
    paths:
      - 'frontend/**'
      - '.github/workflows/deploy-app.yml'
  pull_request:
    branches: [ main ]
    paths:
      - 'frontend/**'
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "app-deploy"
  cancel-in-progress: false

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    container:
      image: node:20-alpine
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          apk add --no-cache git
          echo "Node version: $(node --version)"
          echo "NPM version: $(npm --version)"
          echo "Current directory: $(pwd)"
          echo "Directory contents: $(ls -la)"
          npm install

      - name: Build application
        working-directory: ./frontend
        run: npm run build

      - name: Deploy to docs directory
        run: |
          # Backup existing docs content
          mkdir -p docs-backup
          cp -r docs/* docs-backup/ || true
          
          # Copy built React app to docs directory
          cp -r frontend/dist/* docs/
          
          # Restore CNAME file
          echo "evmore.droo.foo" > docs/CNAME
          
          # Commit and push changes
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add docs/
          git commit -m "Deploy React app to docs directory" || echo "No changes to commit"
          git push origin main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
